# Generated by Django 4.1.7 on 2023-03-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POIStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.IntegerField(verbose_name='POI序号')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('thumbsup', models.IntegerField(verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '地点点赞',
                'verbose_name_plural': '地点点赞',
                'db_table': 'poi_stars',
            },
        ),
        migrations.CreateModel(
            name='UserStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, verbose_name='昵称')),
                ('poi', models.IntegerField(verbose_name='POI序号')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('timestamp', models.TimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
                'db_table': 'user_stars',
            },
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40, verbose_name='昵称')),
                ('poi', models.IntegerField(verbose_name='POI序号')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('timestamp', models.TimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户浏览',
                'verbose_name_plural': '用户浏览',
                'db_table': 'user_views',
            },
        ),
    ]
