# Generated by Django 4.1.7 on 2023-03-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstar',
            name='timestamp',
            field=models.CharField(max_length=20, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='userview',
            name='timestamp',
            field=models.CharField(max_length=20, verbose_name='时间'),
        ),
    ]
